basePath: /
host: ws-rayfan2024-7c90fe3029b2.herokuapp.com/
info:
  contact:
    email: rayfana09@gmail.com
    name: API Support
    url: https://github.com/rayfanaqbil
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
